version: '3.6'

services:

  alpine-latest:
    image: localhost:5000/rjchicago/docker-duper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SOURCE_REGISTRY=
      - DESTINATION_REGISTRY=localhost:5000
      - IMAGE=alpine
      - TAG=

  alpine-edge:
    image: localhost:5000/rjchicago/docker-duper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SOURCE_REGISTRY=
      - DESTINATION_REGISTRY=localhost:5000
      - IMAGE=alpine
      - TAG=edge

  registry-2:
    image: localhost:5000/rjchicago/docker-duper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SOURCE_REGISTRY=
      - DESTINATION_REGISTRY=localhost:5000
      - IMAGE=registry
      - TAG=2

