version: '3.6'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
  ui:
    image: parabuzzle/craneoperator:2.2.5
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
    ports:
      - "8080:80"
